### ISSUE TITLE
Program crashes after running for a few days

### ISSUE THREAD

**Issue by fterh** [fterh/sneakpeek#13]
The bot is running on an Ubuntu 18.10 x64 Digitalocean droplet using the command `nohup python3 -m pipenv run invoke start &`.

After a few days of running, it crashes. This is the output log:

```
Starting main
Starting scan
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    schedule.run_pending()
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "main.py", line 22, in start
    scan(reddit.subreddit(config.SUBREDDIT))
  File "/root/sneakpeek/scan.py", line 12, in scan
    for submission in subreddit.new(limit=config.LIMIT):
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/praw/reddit.py", line 391, in get
    data = self.request('GET', path, params=params)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/praw/reddit.py", line 506, in request
    params=params)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/prawcore/sessions.py", line 116, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/prawcore/sessions.py", line 101, in _make_request
    params=params)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/prawcore/rate_limit.py", line 35, in call
    kwargs['headers'] = set_header_callback()
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/prawcore/sessions.py", line 145, in _set_header_callback
    self._authorizer.refresh()
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/prawcore/auth.py", line 328, in refresh
    password=self._password)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/prawcore/auth.py", line 138, in _request_token
    response = self._authenticator._post(url, **data)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/prawcore/auth.py", line 31, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 503 HTTP response
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/program.py", line 363, in run
    self.execute()
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/program.py", line 532, in execute
    executor.execute(*self.tasks)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "/root/sneakpeek/tasks.py", line 7, in start
    c.run("ENV=prod python main.py")
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/context.py", line 94, in run
    return self._run(runner, command, **kwargs)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/runners.py", line 271, in run
    return self._run_body(command, **kwargs)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/runners.py", line 365, in _run_body
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException:
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'echo': None,
            'input_': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>,
            'output': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>},
 'target': <bound method Runner.handle_stdin of <invoke.runners.Local object at 0x7fbbf201aba8>>}

Traceback (most recent call last):

  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)

  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/runners.py", line 641, in handle_stdin
    data = self.read_our_stdin(input_)

  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/runners.py", line 601, in read_our_stdin
    bytes_ = input_.read(bytes_to_read(input_))

OSError: [Errno 9] Bad file descriptor
```

**Comment by xlanor** [comment]
Are you opening a file and not closing it properly anywhere?

**Comment by fterh** [comment]
Nope. I suspect it ran out of memory or something, because this's happened before, and it's always after a few days.

@yleong suggested running it as a system service I think, so this might be low priority if we're able to rewrite how the program is run.

**Comment by xlanor** [comment]
If you are planning to do a refactor, I strongly suggest that the files be regrouped, minimally, into an src/ drive and tests/ drive respectively for source code and test files.

**Comment by yleong** [comment]
The Reddit API was returning a HTTP response status of `503 Service Unavailable` when `praw` is trying to call `response = self._authenticator._post(url, **data)` to get new submissions.
The relevant line is `prawcore.exceptions.ResponseException: received 503 HTTP response`. (source [here](https://github.com/praw-dev/prawcore/blob/master/prawcore/exceptions.py#L38)) The rest of it looks to be this exception being thrown up the stack until it hits some sort of stdin handler.
I think we can catch this response [here](https://github.com/fterh/sneakpeek/blob/master/scan.py#L12) and retry the request after waiting for a bit, since 503 sometimes indicates an overloaded server. This can be done in addition to running it under `pm2` or systemd to ensure higher uptime.

Regarding the code refactor, I am not familiar with Python project structure, but what @xlanor suggested makes sense.

**Comment by yleong** [comment]
Are there more crash logs available?

**Comment by fterh** [comment]
Yup!

[nohup.txt](https://github.com/fterh/sneakpeek/files/2914852/nohup.txt)

**Comment by yleong** [comment]
Ricemedia handler also threw exception. I have opened #19 to track that separately.

**Comment by fterh** [comment]
@yleong I checked the PRs and I saw you merged one which fixes this. Can I close this issue and prepare to create a new release?

**Comment by yleong** [comment]
Sure. If the program still crashes maybe we can reopen.

**Comment by fterh** [comment]
Okay, closing this for now. @yleong @xlanor I'm pushing v0.5.0-beta into production, I've ran manual tests and it looks good.
